name: Daily Watchdog Timer
on:
  schedule:
    # This runs the script twice a day automatically
    - cron: '0 4,11 * * *'
  workflow_dispatch: # This allows you to click a button to test it right now

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: python watchdog.py
        env:
          SERPAPI_KEY: ${{ a26cba36b987618851ca736193c22003f8121f57d3bfac9ef25dfdeb3a5c8a7e }}
          GMAIL_USER: ${{ ChIJ7xV3YrbcBjsRY-mRAuvuDvk }}
          GMAIL_PASS: ${{ vaithiyanathanmuneeswaran@gmail.com }}
